version: "3.9"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      STRING_SESSION: $STRING_SESSION
      HANDLER: $HANDLER
      TZ: $TZ
    restart: on-failure
